name: Build

on:
  pull_request:
  workflow_call:

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os:
          [
            ubuntu-22.04,
            ubuntu-24.04,
            macos-14,
            macos-15,
            windows-2022,
            windows-2025
          ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2

      - if: ${{ !contains(matrix.os, 'macos') }}
        name: Install  (Linux and Windows)
        uses: xmake-io/github-action-setup-xmake@b48f0b6b07917d96d0dcb9c6e54a14db31936560 # 1.2.1

      - if: contains(matrix.os, 'macos')
        name: Install xmake (macOS)
        run: |
          # Faster than using the xmake-io/github-action-setup-xmake action
          brew install xmake

      - if: contains(matrix.os, 'ubuntu')
        name: Install qt dependencies (Ubuntu)
        run: |
          # TODO:Is the qt6widgets package broken?
          sudo apt update && sudo apt install -y libglfw3-dev libgles2-mesa-dev

      - if: contains(matrix.os, 'windows')
        name: Configure xmake (Windows)
        run: |
          # The default platform is mingw, which is not supported by qt6widgets
          xmake f -p windows -a x64 -y

      - name: Build with xmake
        shell: bash
        run: |
          xmake -y
